 Feff 6L.02
 Copper example
 Calculating potentials and phases...
     free atom potential and density for atom type    0
     free atom potential and density for atom type    1
     overlapped potential and density for unique potential    0
     overlapped potential and density for unique potential    1
     muffin tin radii and interstitial parameters
     phase shifts for unique potential    0
     phase shifts for unique potential    1
 Preparing plane wave scattering amplitudes...
   nncrit in prcrit       9
 Searching for paths...
     Rmax  5.0000  keep and heap limits   0.0000000   0.0000000
    Preparing neighbor table
     nfound  nheap  nheapx  nsc    r
     Paths found      306   (nheapx, nbx      43   3)
 Eliminating path degeneracies...
     Plane wave chi amplitude filter   2.50%
     Unique paths      7,  total paths     282
 Calculating EXAFS parameters...
     Curved wave chi amplitude ratio   4.00%
     Discard feff.dat for paths with cw ratio <   2.67%
     path  cw ratio     deg    nleg  reff
       1   100.000    12.000     2   2.5527
       2    22.980     6.000     2   3.6100
       3    10.585    48.000     3   3.8290
       4     8.646    48.000     3   4.3577
       5    55.405    24.000     2   4.4213
       6    10.626    48.000     3   4.7633
       7    21.810    96.000     3   4.7633
     7 paths kept,    7 examined.
 Calculating chi...
     Use all paths with cw amplitude ratio   4.00%
     Use Debye-Waller factors from files.dat.  S02  1.000
     feff0001.dat     100.0000
     feff0002.dat      22.9800
     feff0003.dat      10.5850
     feff0004.dat       8.6460
     feff0005.dat      55.4050
     feff0006.dat      10.6260
     feff0007.dat      21.8100
  ff2chi done,    7/   7 paths used.
 Feff done.  Have a nice day.
